### PR TITLE
Fix formatting for `fuelup-init.sh`

### LINKED ISSUE #53: format `fuelup-init.sh`
Accidentally formatted with tabs - we should reformat it using 2 spaces instead.

### PR DESCRIPTION
**Pull request by binggh**
Closes #53 

Ran this command:

```sh
shfmt -i 2 -ci -w fuelup-init.sh
```

### CODE REVIEW

**Review by adlerjohn — COMMENTED** [review]
`rustup` uses 4 spaces, for reference.

Looking at it now, I'm having trouble parsing indentation. I personally would prefer 4 spaces, but not going to veto 2.

File: fuelup-init.sh [hunk 1]
```diff
@@ -15,7 +15,7 @@ main() {
     check_cargo_bin forc-fmt
     check_cargo_bin forc-explore
     check_cargo_bin forc-lsp
-    check_cargo_bin fuel-core 
+    check_cargo_bin fuel-core
```
Comment (mitchmindtree) [inline fuelup-init.sh:18]: love it

**Review by mitchmindtree — APPROVED** [review]
