### PR TITLE
Show installed toolchains if a user tries to set an incorrect toolchain name to the default.

### LINKED ISSUE #557: fuelup default <name>
### Problem you are trying to solve

When choosing a name that does not exist either prompt the user to use the `fuelup show` command to check the toolchains or preferably automatically show the installed toolchains below.

image
image
Capitalize the `d` in `default`

image

### Solution you'd like

When choosing a name that does not exist either prompt the user to use the `fuelup show` command to check the toolchains or preferably automatically show the installed toolchains below.

### Notes

_No response_

### PR DESCRIPTION
**Pull request by JoshuaBatty**
closes #557

### CODE REVIEW

File: tests/check.rs [hunk 1]
```diff
@@ -27,6 +27,7 @@ fn fuelup_check() -> Result<()> {
         let output = cfg.fuelup(&["check"]);
         let stripped = strip_ansi_escapes::strip(output.stdout);
         let stdout = String::from_utf8_lossy(&stripped);
+        println!("\n{}", &stdout);
```
Comment (sdankel) [inline tests/check.rs:30]:
```suggestion
```

**Review by sdankel — APPROVED** [review]

File: tests/check.rs (hunk 1 above)
Comment (JoshuaBatty) [reply tests/check.rs:30]: Good catch :)

**Review by sdankel — APPROVED** [review]
