### PR TITLE
Do not download self update if it is the same version

### LINKED ISSUE #555: `fuelup self update` downloading the same version
### Problem you are trying to solve

Despite having the same version already installed we appear to download the same release again.

image

### Solution you'd like

This may be an intentional decision to “fix” the tool by reinstalling if something is broken, if not then add a check on the version before downloading again to save on bandwidth and work done on the filesystem

### Notes

_No response_

### PR DESCRIPTION
**Pull request by crodas**
Fixes #555

After:

image

### CODE REVIEW

File: src/file.rs [hunk 1]
```diff
@@ -9,6 +10,21 @@ pub(crate) fn is_executable(file: &Path) -> bool {
     file.is_file() && file.metadata().unwrap().permissions().mode() & 0o111 != 0
 }
 
+pub(crate) fn get_bin_version(exec_path: &Path) -> Option<Version> {
```
Comment (sdankel) [inline src/file.rs:13]: 💟

File: src/ops/fuelup_self.rs [hunk 2]
```diff
@@ -27,6 +27,14 @@ pub fn self_update() -> Result<()> {
 
     let fuelup_bin = fuelup_bin();
 
+    if !force && get_bin_version(&fuelup_bin) == Some(download_cfg.version.clone()) {
+        info!(
+            "fuelup is already up to date at version {}",
```
Comment (sdankel) [inline src/ops/fuelup_self.rs:32]: nit:
```suggestion
            "Already up to date (fuelup v{})",
```

File: src/ops/fuelup_show.rs [hunk 3]
```diff
@@ -1,11 +1,12 @@
-use anyhow::{bail, Result};
+use anyhow::Result;
 use component::{self, Components};
 use semver::Version;
 use std::collections::HashMap;
-use std::path::Path;
+
```
Comment (sdankel) [inline src/ops/fuelup_show.rs:5]:
```suggestion
```

File: src/ops/fuelup_show.rs [hunk 4]
```diff
@@ -1,11 +1,12 @@
...
 use std::str::FromStr;
 use tracing::info;
```
Comment (sdankel) [inline src/ops/fuelup_show.rs:8]:
```suggestion
```

File: src/ops/fuelup_show.rs [hunk 5]
```diff
@@ -17,33 +18,6 @@ use crate::{
...
-                    Ok(version)
-                }
-                None => {
-                    bail!("Error getting version string");
-                }
-            }
-        }
-        Err(e) => {
-            if component_executable.exists() {
-                bail!("execution error - {}", e);
```
Comment (sdankel) [inline src/ops/fuelup_show.rs:39]: This is still a useful error. Could we incorporate this error handling into `get_bin_version` and have it return a Result instead of Option?

File: src/toolchain.rs [hunk 6]
```diff
@@ -304,7 +308,7 @@ impl Toolchain {
         let fuelup_bin = fuelup_bin();
         if !fuelup_bin.is_file() {
             info!("fuelup not found - attempting to self update");
```
Comment (sdankel) [inline src/toolchain.rs:310]: This doesn't seem like it should be possible 🤣 If someone wanted to install it only from cargo, this would not update the cargo version, and install fuelup in the home directory, which is probably not what they want. 

In that case I think we should give an error message like `fuelup cannot update itself because it was installed by a package manager. For full functionality, visit https://docs.fuel.network/docs/fuelup/installation and re-install.`

File: tests/self.rs [hunk 7]
```diff
@@ -5,12 +5,22 @@ use testcfg::FuelupState;
...
+        let output = cfg.fuelup(&["self", "update", "--force"]);
         let expected_stdout_starts_with = "Fetching binary from";
         assert!(output.stdout.starts_with(expected_stdout_starts_with));
     })?;
 
     Ok(())
 }
+
+#[test]
+fn fuelup_self_update_latest() -> Result<()> {
```
Comment (sdankel) [inline tests/self.rs:18]: 👍

**Review by sdankel — COMMENTED** [review]
Mostly nits, thanks for doing this!

File: src/file.rs [hunk 8]
```diff
@@ -1,14 +1,38 @@
...
+use semver::Version;
+use std::{fs, io, os::unix::fs::PermissionsExt, path::Path};
 
 #[cfg(unix)]
 pub(crate) fn is_executable(file: &Path) -> bool {
     file.is_file() && file.metadata().unwrap().permissions().mode() & 0o111 != 0
 }
 
+#[derive(Debug, thiserror::Error)]
+pub(crate) enum BinError {
```
Comment (sdankel) [inline src/file.rs:11]: This is much better!

File: src/ops/fuelup_check.rs [hunk 9]
```diff
@@ -56,34 +57,22 @@ fn format_version_comparison(current_version: &Version, latest_version: &Version
...
-                        "",
-                        bold(plugin),
-                        format_version_comparison(&version, latest_version)
-                    );
-                }
-                None => {
-                    info!("{:>4}- {} - Error getting version string", "", plugin);
-                }
-            };
+    match get_bin_version(plugin_executable) {
```
Comment (sdankel) [inline src/ops/fuelup_check.rs:60]: nit: we can make it even shorter! This function never returns an error, so doesn't need to return an empty result.

```rust
fn check_plugin(plugin_executable: &Path, plugin: &str, latest_version: &Version) {
    let version_or_err = match get_bin_version(plugin_executable) {
        Ok(version) => format_version_comparison(&version, latest_version),
        Err(err) => err.to_string()
    };
    info!("{:>4}- {} - {}", "", plugin, version_or_err);
}
```

File: src/ops/fuelup_check.rs [hunk 10]
```diff
@@ -121,36 +110,24 @@ fn check_toolchain(toolchain: &str, verbose: bool) -> Result<()> {
...
-
+                Err(e) => {
+                    error!(
+                        "{:>2}{} - Error getting version string: {}",
+                        "",
+                        bold(&component.name),
+                        e.to_string()
+                    );
+                }
+            }
```
Comment (sdankel) [inline src/ops/fuelup_check.rs:130]: Same thing here:

```rust 
            let version_text = match get_bin_version(&component_executable) {
                Ok(version) => format_version_comparison(&version, latest_version),
                Err(err) => err.to_string(),
            };
            info!("{:>2}{} - {}", "", bold(&component.name), version_text);
```

**Review by sdankel — COMMENTED** [review]
Looking good, just a couple nits 👍

**Review by sdankel — APPROVED** [review]
